{
 "title": "Lab 4 - 4 Golden Signals",
 "tags": [
  "lab4",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latence - Temps de Reponse",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, api_request_duration_seconds_bucket)",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Trafic - Requetes par Seconde",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "rate(api_requests_total[1m])", "legendFormat": "RPS" }
   ]
  },
  {
   "title": "Erreurs - Taux d'Erreur",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(api_requests_total{status=~\"4..|5..\"}[1m]) / rate(api_requests_total[1m]) * 100",
     "legendFormat": "Error Rate %"
    }
   ]
  },
  {
   "title": "Saturation - Requetes Actives",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "api_active_requests", "legendFormat": "Active Requests" }
   ]
  }
 ]
}