version: "3.8"
services:
  app:
    build: .
    command: python app/console.py
    volumes:
      - ./bd.sqlite3:/app/bd.sqlite
    stdin_open: true
    tty: true
    environment:
      - PYTHONUNBUFFERED=1
  tests:
    build: .
    command: pytest