name: Lab 2 CI Pipeline

on:
  push:
    branches:
      - main
      - lab2
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: lab2_db
          POSTGRES_USER: lab2_user
          POSTGRES_PASSWORD: lab2_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client curl
        python -m pip install --upgrade pip
        pip install -r "Étape 1 (Labs 0-2)/requirements.txt"

    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h localhost -p 5432 -U lab2_user; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done

    - name: Run unit tests
      run: python -m pytest "Étape 1 (Labs 0-2)/tests/test_unitaires.py" -v
      env:
        DATABASE_URL: postgresql://lab2_user:lab2_password@localhost:5432/lab2_db

    - name: Run integration tests
      run: python -m pytest "Étape 1 (Labs 0-2)/tests/test_integration.py" -v
      env:
        DATABASE_URL: postgresql://lab2_user:lab2_password@localhost:5432/lab2_db

    - name: Run main script
      run: |
        cd "Étape 1 (Labs 0-2)"
        python app/main.py

    - name: Skip E2E tests
      run: echo "tests e2e pas besoin pour lab2"


